tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "autoconf"
brew "bash"
brew "coreutils"
brew "curl"
brew "gcc"
brew "git"
brew "gnupg"
brew "nvim"
brew "openssl"
brew "postgres"
brew "redis"
brew "ripgrep"
brew "stow"

cask "1password"
cask "alfred"
cask "hammerspoon"
cask "shiftit"
cask "signal"
cask "slack"
cask "telegram"
cask "visual-studio-code"
